// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NfeProcessor.Data;

#nullable disable

namespace nfe_processor_app.Migrations
{
    [DbContext(typeof(NfeDbContext))]
    [Migration("20251110155907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("NfeProcessor.Models.Nfe", b =>
                {
                    b.Property<string>("AccessKey")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IcmsValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IpiValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuerCNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipientCNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("TEXT");

                    b.HasKey("AccessKey");

                    b.ToTable("Nfes");
                });

            modelBuilder.Entity("NfeProcessor.Models.NfeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeAccessKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NfeAccessKey");

                    b.ToTable("NfeProducts");
                });

            modelBuilder.Entity("NfeProcessor.Models.NfeProduct", b =>
                {
                    b.HasOne("NfeProcessor.Models.Nfe", "Nfe")
                        .WithMany("Products")
                        .HasForeignKey("NfeAccessKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nfe");
                });

            modelBuilder.Entity("NfeProcessor.Models.Nfe", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
